# Generated by Django 3.2.1 on 2021-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_account_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='magick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='skin_color',
            field=models.TextField(default='white'),
        ),
        migrations.AddField(
            model_name='character',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vitality',
            field=models.IntegerField(default=0),
        ),
    ]
