# Generated by Django 3.2.1 on 2021-06-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210525_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skin_color',
        ),
        migrations.AddField(
            model_name='character',
            name='skin',
            field=models.TextField(default='white'),
        ),
        migrations.AlterField(
            model_name='character',
            name='texture',
            field=models.TextField(default='random'),
        ),
    ]
